# Generated by Django 4.2.11 on 2026-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_job_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('error', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
