# Generated by Django 4.2.11 on 2026-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_deadletterjob_last_retry_at_alter_deadletterjob_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
