# Generated by Django 4.2.11 on 2026-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
