# Generated by Django 4.2.11 on 2026-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_last_heartbeat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lease_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
