# Generated by Django 4.2.11 on 2026-06-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_lease_expiration_job_lease_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='lease_expiration',
            new_name='lease_expires_at',
        ),
    ]
