# Generated by Django 4.2.11 on 2026-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_lease_expiration_job_lease_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deadletterjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='deadletterjob',
            name='original_job_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
