# Generated by Django 4.2.11 on 2026-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_outboxevent_remove_deadletterjob_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='aggregate_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
