# Generated by Django 4.2.11 on 2026-06-19 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_outboxevent_aggregate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
